# Site settings
title: Yiwei Zhang, SwiftUI + React Native + Node.js
description: "A blog about Yiwei Zhang."
baseurl: "/zywkloo.github.io" # for test: remove string '/space-jekyll-template' to ''
url: "https://zywkloo.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: Yiwei Zhang
user_title: SwiftUI/React Native/Node.js Developer
email: yiweizhangca@gmail.com
twitter_username: zywkloo
github_username:  zywkloo
gplus_username: 116814196032329811422
linkedin_public_url: yiweiZ315
profile_picture: https://github.com/zywkloo/zywkloo.github.io/raw/master/assets/img/sharding-gerenciamento-usuarios/Avatar.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: AI Ethics
      url: /sharding/
      key_trigger: a
    - title: Space Walkthrough
      url: /space/
      key_trigger: p
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: Xchangerator:All-in-one iOS app for exchange rates
    url: https://xchangerator.com
  - name: cuHacking20:CSI Murder on 2nd floor, w/ Plotly.js
    url: https://devpost.com/software/murder-on-2nd-floor-web-forensic-analyzer
  - name: cuHacking19:Hacker Pizza Order System, w/ AWS Connect.
    url: https://devpost.com/software/cuhackingamazonconnect
  - name: TutorOcean Android app w/ React Native.
    url: https://play.google.com/store/apps/details?id=com.tutorocean
  - name: TutorOcean iOS app w/ React Native.
    url: https://apps.apple.com/app/apple-store/id1480876532
  - name: Mobile Game Wild Dunk(全民大灌篮).
    url: https://www.youtube.com/watch?time_continue=6&v=ysmp5vK4R_c
  - name: GameAI:Tank Tournament w/ Pygame.
    url: https://github.com/zywkloo/Tank-Game-AI-Tournament
  - name: Insomnia-Dungeon. Mini game w/ Pygame.
    url: https://github.com/zywkloo/Insomnia-Dungeon
   



# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
